version: "3.9"
services:
  api:
    build:
        context: .
        dockerfile: 'Dockerfile.local'
    tty: true
    command: "gow run ./src"
    volumes: 
      - './:/usr/src/app'
    networks:
      goweather_net:
    depends_on: 
      redis:
        condition: service_healthy

  redis:
    image: redis:6.2.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - redis-data:/data/redis
    networks:
      goweather_net:

volumes:
  redis-data:
networks: 
  goweather_net:
    name: goweather_net
